<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="28dba6a0-a8a2-4129-8fd6-2757dd76bf9c" name="griddy@SKIM 2012-10-05 21:06:43" runUser="skim\griddy" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="bc4360a7-4d1e-404e-9bc3-72ad9fe5cb82">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="griddy_SKIM 2012-10-05 21_06_43">
      <DeploymentItem filename="C:\careers\careers\bin\careers.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-10-05T21:06:43.7334988+02:00" queuing="2012-10-05T21:06:43.7935023+02:00" start="2012-10-05T21:06:43.7975025+02:00" finish="2012-10-05T21:07:23.5367754+02:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="VacancyDAO_Test" storage="c:\careers\testcases\bin\debug\testcases.dll" id="e4c7bff8-cda3-0397-d076-d8b91c7dd823">
      <Execution id="db809e58-fc84-404c-9ba7-170d43e79596" />
      <TestMethod codeBase="C:/careers/TestCases/bin/Debug/TestCases.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestCases.VacancyDAOTest, TestCases, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="VacancyDAO_Test" />
      <AspNet webSiteUrl="http://localhost:12075/">
        <Host pathToWebApp="C:\careers\careers" webAppRoot="/" />
      </AspNet>
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="e4c7bff8-cda3-0397-d076-d8b91c7dd823" executionId="db809e58-fc84-404c-9ba7-170d43e79596" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="db809e58-fc84-404c-9ba7-170d43e79596" testId="e4c7bff8-cda3-0397-d076-d8b91c7dd823" testName="VacancyDAO_Test" computerName="SKIM" startTime="2012-10-05T21:06:43.8005027+02:00" endTime="2012-10-05T21:07:23.4217689+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="db809e58-fc84-404c-9ba7-170d43e79596">
      <Output>
        <ErrorInfo>
          <Message>The test started running in response to request 'http://localhost:12075/', but an error occurred before the test finished executing: Unable to connect to the remote server. </Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>